language: node_js
node_js:
  - "8"
sudo: false
cache:
  directories:
    - "node_modules"
script: npm run build
git:
  submodules: false
before_install:
  - "git submodule update --init --recursive"
  - "git submodule foreach --recursive git reset --hard origin/artifacts"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master